name: cssr
channels:
  - conda-forge
dependencies:
 - pip
 - python=3.12
 - scikit-learn
 - shapely
 - dash
 - dash-bootstrap-components
 - dash-bootstrap-templates
 - matplotlib
 - numpy
 - pandas
 - plotly
 - python-kaleido
 - nbformat
 