name: cssr
channels:
  - conda-forge
dependencies:
 - pip
 - python
 - scikit-learn
 - dash
 - dash-bootstrap-components
 - dash-bootstrap-templates=1.0.8
 - matplotlib
 - numpy
 - pandas
 - plotly
 - nbformat>=4.2.0
 - gunicorn
